#!/bin/bash

if [[ ! -f README.md || ! -d ./rfd ]]; then
	echo "Must be run in root directory"
	exit 1
fi

if ls -d rfd/*/ > /dev/null 2>&1; then
    echo "Proceeding to check RFDs"
else
    echo "No RFDs exist"
	exit 0
fi

for file in rfd/[0-9][0-9][0-9][0-9]/README.md; do
	if ! grep -q "$file" README.md; then
		echo "README.md is missing the $file reference."
		exit 1
	fi

	if ! grep -q -w "^# RFD" "$file"; then
		echo "${file}: the Title is missing or it's formatted incorrectly."
		exit 1
	fi

	sections=("Introduction" "Problem" "Proposal" "Impact")
	for section in "${sections[@]}"; do
		if ! grep -q -w "^## $section$" "$file"; then
			echo "${file}: the $section section is missing or it's formatted incorrectly. check for whitespace"
			exit 1
		fi
	done

	metadata=("authors:" "state:" "discussion:")
	for meta in "${metadata[@]}"; do
		if ! grep -q -w "^$meta" "$file"; then
			echo "${file}: the $meta metadata is missing or it's formatted incorrectly."
			exit 1
		fi
	done
done